#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# 03 — Create Annual Policies
# ═══════════════════════════════════════════════════════════════
#
# MUTATES: Creates 2 new policies in Keygen.
#
# Clones all attributes from the monthly policy snapshots,
# then overrides: name, duration (379 days), transferStrategy,
# and renewalBasis. Requires product relationship.
#
# Prereq: Run 02-update-monthly-policies.sh first
#         (needs updated monthly snapshots to clone from).
#
# Output files in snapshots/:
#   policy-individual-annual-created.json
#   policy-business-annual-created.json
#   annual-policy-ids.env    (sourced by downstream scripts)
# ═══════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config.sh"

load_keygen_token
load_current_policy_ids

# ── Pre-flight checks ─────────────────────────────────────────
INDIV_SNAPSHOT="${SNAPSHOTS_DIR}/policy-individual-monthly-updated.json"
BIZ_SNAPSHOT="${SNAPSHOTS_DIR}/policy-business-monthly-updated.json"

if [[ ! -f "${INDIV_SNAPSHOT}" || ! -f "${BIZ_SNAPSHOT}" ]]; then
  log_err "Monthly policy snapshots not found."
  log_err "Run 02-update-monthly-policies.sh first."
  exit 1
fi

log_step "Creating Annual Policies"

# ── Helper: build create body by cloning from snapshot ────────
# Reads a monthly policy snapshot, clones writeable attributes,
# overrides name + duration + transferStrategy + renewalBasis,
# and attaches the product relationship.
build_annual_body() {
  local snapshot_file="$1"
  local new_name="$2"
  local new_duration="$3"

  node -e "
    const fs = require('fs');
    const snapshot = JSON.parse(fs.readFileSync(process.argv[1], 'utf8'));
    const src = snapshot.data.attributes;

    // Attributes that are read-only or auto-derived — don't send
    const readOnly = new Set([
      'created', 'updated', 'encrypted', 'metadata'
    ]);

    const attrs = {};
    for (const [key, val] of Object.entries(src)) {
      if (!readOnly.has(key) && val !== null) {
        attrs[key] = val;
      }
    }

    // Override for annual policy
    attrs.name = process.argv[2];
    attrs.duration = parseInt(process.argv[3], 10);
    attrs.transferStrategy = 'RESET_EXPIRY';
    attrs.renewalBasis = 'FROM_EXPIRY';

    const body = {
      data: {
        type: 'policies',
        attributes: attrs,
        relationships: {
          product: {
            data: {
              type: 'products',
              id: '${KEYGEN_PRODUCT_ID}'
            }
          }
        }
      }
    };

    process.stdout.write(JSON.stringify(body));
  " "${snapshot_file}" "${new_name}" "${new_duration}"
}

# ── 1. Create Individual Annual ───────────────────────────────
log_info "Creating Individual Annual policy..."
BODY_INDIVIDUAL=$(build_annual_body "${INDIV_SNAPSHOT}" "Individual Annual" "${DURATION_ANNUAL}")
INDIV_ANN_OUT="${SNAPSHOTS_DIR}/policy-individual-annual-created.json"
keygen_post "/policies" "${BODY_INDIVIDUAL}" "${INDIV_ANN_OUT}"
json_format "${INDIV_ANN_OUT}"

NEW_ID_INDIVIDUAL=$(json_field "${INDIV_ANN_OUT}" "data.id")
NEW_NAME_INDIVIDUAL=$(json_field "${INDIV_ANN_OUT}" "data.attributes.name")
NEW_DURATION_INDIVIDUAL=$(json_field "${INDIV_ANN_OUT}" "data.attributes.duration")
log_ok "Created: ${NEW_NAME_INDIVIDUAL} (${NEW_ID_INDIVIDUAL}), duration=${NEW_DURATION_INDIVIDUAL}"

# ── 2. Create Business Annual ─────────────────────────────────
log_info "Creating Business Annual policy..."
BODY_BUSINESS=$(build_annual_body "${BIZ_SNAPSHOT}" "Business Annual" "${DURATION_ANNUAL}")
BIZ_ANN_OUT="${SNAPSHOTS_DIR}/policy-business-annual-created.json"
keygen_post "/policies" "${BODY_BUSINESS}" "${BIZ_ANN_OUT}"
json_format "${BIZ_ANN_OUT}"

NEW_ID_BUSINESS=$(json_field "${BIZ_ANN_OUT}" "data.id")
NEW_NAME_BUSINESS=$(json_field "${BIZ_ANN_OUT}" "data.attributes.name")
NEW_DURATION_BUSINESS=$(json_field "${BIZ_ANN_OUT}" "data.attributes.duration")
log_ok "Created: ${NEW_NAME_BUSINESS} (${NEW_ID_BUSINESS}), duration=${NEW_DURATION_BUSINESS}"

# ── 3. Persist New Policy IDs ─────────────────────────────────
IDS_FILE="${SNAPSHOTS_DIR}/annual-policy-ids.env"
cat > "${IDS_FILE}" <<EOF
# Generated by 03-create-annual-policies.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Sourced by downstream migration scripts
POLICY_ID_INDIVIDUAL_ANNUAL="${NEW_ID_INDIVIDUAL}"
POLICY_ID_BUSINESS_ANNUAL="${NEW_ID_BUSINESS}"
EOF

log_ok "Saved annual policy IDs to ${IDS_FILE}"

# ── Summary ───────────────────────────────────────────────────
log_step "Annual Policy Creation Complete"
echo ""
echo "  New policies created:"
echo "  ├── Individual Annual  ${NEW_ID_INDIVIDUAL}"
echo "  │   duration=${DURATION_ANNUAL}s (379 days)"
echo "  └── Business Annual    ${NEW_ID_BUSINESS}"
echo "      duration=${DURATION_ANNUAL}s (379 days)"
echo ""
echo "  All 4 policies now exist:"
echo "  ├── Individual Monthly  ${POLICY_ID_INDIVIDUAL}"
echo "  ├── Individual Annual   ${NEW_ID_INDIVIDUAL}"
echo "  ├── Business Monthly    ${POLICY_ID_BUSINESS}"
echo "  └── Business Annual     ${NEW_ID_BUSINESS}"
echo ""
echo "  Review, then run 04-transfer-swr-license.sh"
